os: linux
sudo: required
language: cpp
cache: ccache
compiler:
  - gcc

git:
  depth: 5

env:
 - DEVELOPER_BUILD=false

before_install:
  - sudo apt-get install -y libqt4-dev

before_script:
  - if [ "${DEVELOPER_BUILD}" != "true" ]; then export DEVELOPER_BUILD="false"; fi
  - if [ "${ENABLE_QCH_BUILD}" != "true" ]; then export ENABLE_QCH_BUILD="false"; fi
  - cmake -DUSE_QT4=true -DDEVELOPER_BUILD=${DEVELOPER_BUILD} -DENABLE_QCH_BUILD=${ENABLE_QCH_BUILD} -DENABLE_TESTAPP=true -DENABLE_QML_IMPORT=false -DENABLE_TESTS=false ../telegram-qt

script:
  - make -j3 -k

notifications:
  email: false
